package cn.edu.jlu.ccst.sshclient.ui;

import java.util.ListResourceBundle;

public class RES_en_US extends ListResourceBundle
{
    static final Object[][] contents = {
            {"FILE","File"}, 
            {"TASK","Task"}, 
            {"HELP","Help"},
            {"LANGUAGE","语言"},
            {"CN","中文"},
            {"EN","English"},
            {"COPY","Copy"},
            {"CLOSE","Close"},
            {"CLEAR","Clear"},
            {"CREATE","新建"},
            {"COMPUTER","计算机"},
            {"GROUP","任务组"},
            {"TASK","任务"},
            {"QUIT","退出"},
            {"MODIFY","修改"},
            {"DELETE","删除"},
            {"SERIAL_START_GROUP","串行启动组内所有任务"},
            {"PARALLEL_START_GROUP","同时启动组内所有任务"},
            {"STOP_GROUP","停止组内所有任务"},
            {"START_ALL","启动所有任务"},
            {"STOP_ALL","停止所有任务"},
            {"START_RIGHT_NOW","立即启动任务"},
            {"STOP_ANYWAY","停止当前任务"},
            {"INDEX","索引"},
            {"ABOUT","关于"},
            {"ADD_GROUP","Add Group"},
            {"DELETE_COMPUTER","Delete Computer"},
            {"MODIFY_COMPUTER","Modify Computer"},
            {"ADD_TASK","Add a Task"},
            {"ADD_MANY_TASK","Add many Task"},
            {"DELETE_GROUP","Delete Group"},
            {"MODIFY_GROUP","Modify Group"},
            {"DOWNLOAD_GROUP","下载组内所有任务结果"},
            {"DELETE_TASK","Delete Task"},
            {"MODIFY_TASK","Modify Task"},
            {"EXECLUDE_TASK","执行任务命令"},
            {"STOP_TASK","停止任务命令"},
            {"DOWNLOAD_TASK","下载结果文件"},
            {"UPLOAD_TASK","上传输入文件"},
            {"SHOW_RESULT","查看任务结果"},
            {"ADD_COMPUTER","Add a Computer"},
            {"DELETE_ALL","Delete all Computers"},
            {"TIP_NOT_DELETE","有任务执行，不能删除!"},
            {"TIP_NETWORK","网络连接不可用!"},
            {"TITLE_NETWORK","连接报错"},
            {"TIP_NO_SOURCE","源文件不存在!"},
            {"TITLE_NO_SOURCE","传输报错"},
            {"TIP_FILE_EXIST","目标文件已存在，是否覆盖?"},
            {"TITLE_FILE_EXIST","确认覆盖"},
            {"PROPERTY_CNAME","计算机名"},
            {"PROPERTY_CIP","服务器IP地址"},
            {"PROPERTY_CUSER","帐户名"},
            {"PROPERTY_CPSWD","密码"},
            {"PROPERTY_CLOGIN_TIME","登录时间"},
            {"PROPERTY_MEMO","备注"},
            {"PROPERTY_GNAME","任务组名"},
            {"PROPERTY_WORKDIR","工作目录"},
            {"PROPERTY_CREATE_TIME","创建时间"},
            {"PROPERTY_TNAME","任务名"},
            {"PROPERTY_CMD","任务命令内容"},
            {"PROPERTY_TRESULT","任务结果文件名"},
            {"PROPERTY_TRESULT_URL","任务结果文件路径"},
            {"PROPERTY_TOPTION","任务命令参数"},
            {"PROPERTY_TINPUT","任务输入文件"},
            {"PROPERTY_TINPUT_URL","任务输入文件路径"},
            {"PROPERTY_TEXE_TIME","正在执行中，执行时间"},
            {"PROPERTY_TLAST_TIME","上次任务开始时间"},
            {"PROPERTY_TEND","任务执行结束"},
    };

    public Object[][] getContents()
    {
        return contents;
    }
}
