	
	DROP DATABASE REES;
	
	CREATE DATABASE REES;
	
	USE REES;
	
	CREATE TABLE `REES`.`ADVICE_VIEW`(
        `ADVICE_ID` INT NOT NULL AUTO_INCREMENT,
       `ADVICE` VARCHAR(255),
       `DEVICE_TYPE_ID` VARCHAR(255),
       `DEVICE_TYPE` VARCHAR(255),
        PRIMARY KEY (`ADVICE_ID`)
    );

    CREATE TABLE `REES`.`CENTERHEIGHT_AND_SPEED`(
        `ID` INT NOT NULL AUTO_INCREMENT,
       `CENTER_HEIGHT_EXPRESSION` VARCHAR(255),
       `SPEED_EXPRESSION` VARCHAR(255),
       `THRESHOLD_ID` INT,
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`DEVICE_INFO`(
        `ID` VARCHAR(255) NOT NULL,
       `CENTER_HEIGHT` DECIMAL(19,2),
       `COMPANY_ID` VARCHAR(50),
       `CONTROL_POINT` INT,
       `CREATE_TIME` DATETIME,
       `DEVICE_FACTORY` VARCHAR(255),
       `DEVICE_MODEL` VARCHAR(255),
       `DEVICE_NAME` VARCHAR(255),
       `DEVICE_NUM` VARCHAR(255),
       `DEVICE_TYPE_ID` VARCHAR(255),
       `DEVICE_TYPE_NAME` VARCHAR(255),
       `FACTORY_ID` VARCHAR(255),
       `FILE_PATH` VARCHAR(255),
       `ISDELETE` INT,
       `POWER` DECIMAL(19,2),
       `SORT_INDEX` INT,
       `SPEED` DECIMAL(19,2),
       `WORKSHOP_ID` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
     CREATE TABLE `REES`.`DEVICE_POINT_DATA`(
        `ID` VARCHAR(255) NOT NULL,
       `CREATE_TIME` DATETIME,
       `DATA_INFO` VARCHAR(255),
       `DATA_YEAR` INT,
       `DEVICE_ID` VARCHAR(255),
       `PARAM_ID` VARCHAR(255),
       `POINT_ID` VARCHAR(255),
       `UPDATE_TIME` DATETIME,
       `USER_ID` VARCHAR(255),
       `USER_NAME` VARCHAR(255),
       `WEEK_OF_YEAR` INT,
        PRIMARY KEY (`ID`)
    );

	CREATE TABLE `REES`.`DEVICE_POINT_INFO`(
        `ID` VARCHAR(255) NOT NULL,
       `CONTROL_POINT_NAME` VARCHAR(255),
       `DEVICE_ID` VARCHAR(255),
       `POSITIONX` INT,
       `POSITIONY` INT,
       `STATUS` INT,
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`DEVICE_POINT_PARAM`(
        `ID` VARCHAR(255) NOT NULL,
       `DEVICE_ID` VARCHAR(255),
       `NAME` VARCHAR(255),
       `POINT_ID` VARCHAR(255),
       `SORT_INDEX` INT,
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`DEVICE_TYPE`(
        `ID` VARCHAR(255) NOT NULL,
       `CENTER_HEIGHT` DECIMAL(19,2),
       `POWER` DECIMAL(19,2),
       `SPEED` DECIMAL(19,2),
       `DEVICE_TYPE` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `ERROR_LOG` (
	  `ID` VARCHAR(255) NOT NULL,
	  `DEVICE_NUM` VARCHAR(50) DEFAULT NULL,
	  `DEVICE_NAME` VARCHAR(200) DEFAULT NULL,
	  `DEPT_NAME` VARCHAR(200) DEFAULT NULL,
	  `ERROR_TIME` DATETIME DEFAULT NULL,
	  `REMOVE_TIME` DATETIME DEFAULT NULL,
	  `ISREMOVE` INT(1) DEFAULT '1',
	  `ISALARM` INT(1) DEFAULT '0',
	  `ERROR_DATA` FLOAT(7,0) DEFAULT NULL,
	  `ERROR_THRESH` VARCHAR(200) DEFAULT NULL,
	  `ERROR_PHEN` VARCHAR(1000) DEFAULT NULL,
	  `ERROR_REASON` VARCHAR(1000) DEFAULT NULL,
	  `OPINION` VARCHAR(1000) DEFAULT NULL,
	  PRIMARY KEY (`ID`)
	);

    
    CREATE TABLE `REES`.`FORUM_ISSUE_INFO`(
        `ID` VARCHAR(255) NOT NULL,
       `CREATE_TIME` DATETIME,
       `CREATOR` VARCHAR(255),
       `ISSUE_CONTENT` VARCHAR(255),
       `ISSUE_NAME` VARCHAR(255),
       `ISSUE_STATUS` INT,
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`FORUM_MESSAGE_INFO`(
        `ID` VARCHAR(255) NOT NULL,
       `ISSUE_ID` VARCHAR(255),
       `MESSAGE_CONTENT` VARCHAR(255),
       `MESSAGE_TIME` DATETIME,
       `PUBLISHER` VARCHAR(255),
       `PUBLISHER_DEPT` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
    
     CREATE TABLE `REES`.`GROUP_COMPANY`(
        `ID` VARCHAR(255) NOT NULL,
       `ADDRESS` VARCHAR(255),
       `COMPANY_NAME` VARCHAR(255),
       `CREATE_TIME` DATETIME,
       `PHONE` VARCHAR(255),
       `ROOT_ID` VARCHAR(255),
       `SORT_INDEX` INT,
        PRIMARY KEY (`ID`)
    );

	CREATE TABLE `REES`.`GROUP_FACTORY`(
        `ID` VARCHAR(255) NOT NULL,
       `COMPANY_ID` VARCHAR(255),
       `CREATE_TIME` DATETIME,
       `FACTORY_NAME` VARCHAR(255),
       `PHONE` VARCHAR(255),
       `PRINCIPAL` VARCHAR(255),
       `SORT_INDEX` INT,
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`GROUP_POPEDOM_ROLE`(
        `ID` VARCHAR(255) NOT NULL,
       `KEYWORD` VARCHAR(255),
       `ROLE_ID` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`GROUP_ROLE`(
        `ID` VARCHAR(255) NOT NULL,
       `CREATE_TIME` DATETIME,
       `ROLE_NAME` VARCHAR(255),
       `SORT_INDEX` INT,
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`GROUP_USER`(
        `ID` VARCHAR(255) NOT NULL,
       `COMPANY_ID` VARCHAR(255),
       `CREATE_TIME` DATETIME,
       `DELETEFLAG` INT NOT NULL,
       `EMAIL` VARCHAR(255),
       `FACTORY_ID` VARCHAR(255),
       `OFFICE_PHONE` VARCHAR(255),
       `PASSWORD` VARCHAR(255),
       `PHONE` VARCHAR(255),
       `ROLE_ID` VARCHAR(255),
       `ROLE_NAME` VARCHAR(255),
       `SORT_INDEX` INT,
       `USERCNAME` VARCHAR(255),
       `USER_TYPE` INT,
       `USERNAME` VARCHAR(255),
       `WORKSHOP_ID` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`GROUP_WORKSHOP`(
        `ID` VARCHAR(255) NOT NULL,
       `COMPANY_ID` VARCHAR(255),
       `CREATE_TIME` DATETIME,
       `FACTORY_ID` VARCHAR(255),
       `PHONE` VARCHAR(255),
       `PRINCIPAL` VARCHAR(255),
       `SORT_INDEX` INT,
       `WORKSHOP_NAME` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
     CREATE TABLE `REES`.`NOTICE_INFO`(
        `ID` VARCHAR(255) NOT NULL,
       `NOTICE_CONTENT` VARCHAR(255),
       `NOTICE_EXPIREDTIME` VARCHAR(255),
       `NOTICE_PUBLISHTIME` DATETIME,
       `NOTICE_TITLE` VARCHAR(255),
       `PUBLISHER` VARCHAR(255),
       `PUBLISHER_DEPT` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`NOTICE_READ_INFO`(
        `ID` VARCHAR(255) NOT NULL,
       `NOTICE_ID` VARCHAR(255),
       `USER_ID` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
	
	CREATE TABLE `REES`.`REASON_VIEW`(
        `REASON_ID` INT NOT NULL AUTO_INCREMENT,
       `DEVICE_TYPE_ID` VARCHAR(255),
       `REASON` VARCHAR(255),
       `DEVICE_TYPE` VARCHAR(255),
        PRIMARY KEY (`REASON_ID`)
    );
    
    CREATE TABLE `REES`.`REPORT_PERSON`(
        `ID` VARCHAR(255) NOT NULL,
       `CREATE_TIME` DATETIME,
       `DEPT_ID` VARCHAR(255),
       `ISDELETE` INT,
       `REPORT_CONTENT` VARCHAR(255),
       `REPORT_DATE` DATETIME,
       `REPORT_PERSON` VARCHAR(255),
       `REPORT_STATE` INT,
       `REPORT_SUBJECT` VARCHAR(255),
       `REPORT_TYPE` VARCHAR(255),
       `TEMPLATE_ID` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`REPORT_TEMPLATE`(
        `ID` VARCHAR(255) NOT NULL,
       `CREATE_TIME` DATETIME,
       `REPORT_CONTENT` VARCHAR(255),
       `REPORT_DATE` DATETIME,
       `REPORT_PERSON` VARCHAR(255),
       `REPORT_SUBJECT` VARCHAR(255),
       `REPORT_TYPE` VARCHAR(255),
       `TEMPLATE_NAME` VARCHAR(255),
       `TEMPLATE_PATH` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`RESULT_VIEW`(
        `RESULT_ID` INT NOT NULL AUTO_INCREMENT,
       `DEVICE_TYPE_ID` VARCHAR(255),
       `RESULT` VARCHAR(255),
       `DEVICE_TYPE` VARCHAR(255),
        PRIMARY KEY (`RESULT_ID`)
    );
    
    CREATE TABLE `REES`.`RULE_ADVICE_INFO`(
        `ADVICE_ID` INT NOT NULL AUTO_INCREMENT,
       `ADVICE` VARCHAR(255),
       `DEVICE_TYPE_ID` VARCHAR(255),
        PRIMARY KEY (`ADVICE_ID`)
    );
    
    CREATE TABLE `REES`.`RULE_DEVICE_INFO`(
        `DEVICE_ID` INT NOT NULL AUTO_INCREMENT,
       `DEVICE_TYPE_ID` VARCHAR(255),
       `RESULT_ID` INT UNIQUE,
       `DEVICE_PARAM` VARCHAR(255),
       `THRESHOLD_ID` VARCHAR(255),
       `DEVICE_VAR` VARCHAR(255),
        PRIMARY KEY (`DEVICE_ID`)
    );
    
     CREATE TABLE `REES`.`RULE_INFO`(
        `ID` INT NOT NULL AUTO_INCREMENT,
       `ADVICE_ID` INT,
       `DEVICE_TYPE_ID` VARCHAR(255),
       `REASON_ID` VARCHAR(255),
       `RESULT_ID` VARCHAR(255),
        PRIMARY KEY (`ID`)
    );
    
    CREATE TABLE `REES`.`RULE_REASON_INFO`(
        `REASON_ID` INT NOT NULL AUTO_INCREMENT,
       `DEVICE_TYPE_ID` VARCHAR(255),
       `REASON` VARCHAR(255),
        PRIMARY KEY (`REASON_ID`)
    );
    
    CREATE TABLE `REES`.`RULE_RESULT_INFO`(
        `RESULT_ID` INT NOT NULL AUTO_INCREMENT,
       `DEVICE_TYPE_ID` VARCHAR(255),
       `RESULT` VARCHAR(255),
        PRIMARY KEY (`RESULT_ID`)
    );
    
    CREATE TABLE `REES`.`THRESHOLD_CATEGORY`(
        `CATEGORY_ID` INT NOT NULL AUTO_INCREMENT,
       `CATEGORY_NAME` VARCHAR(255),
       `CREATE_TIME` DATETIME,
        PRIMARY KEY (`CATEGORY_ID`)
    );

	CREATE TABLE `REES`.`THRESHOLD_ITEM`(
        `THRESHOLD_ITEM_ID` INT NOT NULL AUTO_INCREMENT,
       `CREATE_TIME` DATETIME,
       `THRESHOLD_SIGN` INT,
       `THRESHOLD_ITEM_EXPRESSION` VARCHAR(255),
       `THRESHOLD_ITEM_NAME` VARCHAR(255),
       `THRESHOLD_ID` INT NOT NULL,
        PRIMARY KEY (`THRESHOLD_ITEM_ID`)
    );
    
    CREATE TABLE `REES`.`THRESHOLD`(
        `THRESHOLD_ID` INT NOT NULL AUTO_INCREMENT,
       `CREATE_TIME` DATETIME,
       `THRESHOLD_NAME` VARCHAR(255),
       `THRESHOLD_UNIT` VARCHAR(255),
       `THRESHOLD_CATEGORY_ID` INT NOT NULL,
        PRIMARY KEY (`THRESHOLD_ID`)
    );

    INSERT INTO `GROUP_USER` VALUES ('1', NULL, NULL, 0, NULL, NULL, NULL, 'b59c67bf196a4758191e42f76670ceba', NULL, NULL, NULL, 0, '超级管理员', 9, 'admin', NULL);
    
    CREATE VIEW `ADVICE_VIEW` AS SELECT `RULE_ADVICE_INFO`.`ADVICE_ID` AS `ADVICE_ID`,`RULE_ADVICE_INFO`.`ADVICE` AS `ADVICE`,`RULE_ADVICE_INFO`.`DEVICE_TYPE_ID` AS `DEVICE_TYPE_ID`,`DEVICE_TYPE`.`DEVICE_TYPE` AS `DEVICE_TYPE`,`DEVICE_TYPE`.`ID` AS `ID` FROM (`RULE_ADVICE_INFO` JOIN `DEVICE_TYPE`) WHERE (`DEVICE_TYPE`.`ID` = `RULE_ADVICE_INFO`.`DEVICE_TYPE_ID`);
    CREATE VIEW `REASON_VIEW` AS SELECT `RULE_REASON_INFO`.`REASON_ID` AS `REASON_ID`,`RULE_REASON_INFO`.`REASON` AS `REASON`,`RULE_REASON_INFO`.`DEVICE_TYPE_ID` AS `DEVICE_TYPE_ID`,`DEVICE_TYPE`.`DEVICE_TYPE` AS `DEVICE_TYPE` FROM (`RULE_REASON_INFO` JOIN `DEVICE_TYPE`) WHERE (`DEVICE_TYPE`.`ID` = `RULE_REASON_INFO`.`DEVICE_TYPE_ID`);
    CREATE VIEW `RESULT_VIEW` AS SELECT `RULE_RESULT_INFO`.`RESULT_ID` AS `RESULT_ID`,`RULE_RESULT_INFO`.`RESULT` AS `RESULT`,`RULE_RESULT_INFO`.`DEVICE_TYPE_ID` AS `DEVICE_TYPE_ID`,`DEVICE_TYPE`.`DEVICE_TYPE` AS `DEVICE_TYPE` FROM (`RULE_RESULT_INFO` JOIN `DEVICE_TYPE`) WHERE (`DEVICE_TYPE`.`ID` = `RULE_RESULT_INFO`.`DEVICE_TYPE_ID`);
    
    